import 'package:flutter/material.dart';

import '../../l10n/app_localizations.dart';
import '../localization/localization_keys.dart';

String resolveLocalizationKey(BuildContext context, String key) {
  final l10n = AppLocalizations.of(context);
  return switch (key) {
    LocalizationKeys.authEmail => l10n.authEmail,
    LocalizationKeys.authPassword => l10n.authPassword,
    LocalizationKeys.authSignIn => l10n.authSignIn,
    LocalizationKeys.authSigningIn => l10n.authSigningIn,
    LocalizationKeys.authLogout => l10n.authLogout,
    LocalizationKeys.authInvalidCredentials => l10n.authInvalidCredentials,
    LocalizationKeys.authNetworkError => l10n.authNetworkError,
    LocalizationKeys.authServerError => l10n.authServerError,
    LocalizationKeys.authForbiddenRole => l10n.authForbiddenRole,
    LocalizationKeys.authBackendNotConfigured => l10n.authBackendNotConfigured,
    LocalizationKeys.authRequiredField => l10n.authRequiredField,
    LocalizationKeys.authShowPassword => l10n.authShowPassword,
    LocalizationKeys.authHidePassword => l10n.authHidePassword,
    LocalizationKeys.errorGenericBody => l10n.errorGenericBody,
    LocalizationKeys.roleSuperAdmin => l10n.roleSuperAdmin,
    LocalizationKeys.roleSupportAdmin => l10n.roleSupportAdmin,
    LocalizationKeys.roleOnboardingReviewer => l10n.roleOnboardingReviewer,
    LocalizationKeys.roleBillingAdmin => l10n.roleBillingAdmin,
    LocalizationKeys.systemHealthLoadError => l10n.systemHealthLoadError,
    LocalizationKeys.systemHealthActionUnavailable => l10n.systemHealthActionUnavailable,
    LocalizationKeys.supportLoadError => l10n.supportLoadError,
    LocalizationKeys.supportActionUnavailable => l10n.supportActionUnavailable,
    LocalizationKeys.supportActionError => l10n.supportActionError,
    _ => l10n.errorGenericBody,
  };
}

String resolveRegistrationKey(
  BuildContext context,
  String key, {
  Map<String, String> params = const {},
}) {
  final l10n = AppLocalizations.of(context);
  return switch (key) {
    'registrationFilterAll' => l10n.registrationFilterAll,
    'registrationFilterPending' => l10n.registrationFilterPending,
    'registrationFilterNeedsInfo' => l10n.registrationFilterNeedsInfo,
    'registrationFilterAiReviewed' => l10n.registrationFilterAiReviewed,
    'registrationFilterApproved' => l10n.registrationFilterApproved,
    'registrationFilterRejected' => l10n.registrationFilterRejected,
    'registrationFilterHighRisk' => l10n.registrationFilterHighRisk,
    'registrationStatusPending' => l10n.registrationStatusPending,
    'registrationStatusNeedsInfo' => l10n.registrationStatusNeedsInfo,
    'registrationStatusApproved' => l10n.registrationStatusApproved,
    'registrationStatusRejected' => l10n.registrationStatusRejected,
    'registrationStatusCancelled' => l10n.registrationStatusCancelled,
    'registrationStatusUnknown' => l10n.registrationStatusUnknown,
    'registrationRiskLow' => l10n.registrationRiskLow,
    'registrationRiskMedium' => l10n.registrationRiskMedium,
    'registrationRiskHigh' => l10n.registrationRiskHigh,
    'registrationRiskUnknown' => l10n.registrationRiskUnknown,
    'registrationTypeCompany' => l10n.registrationTypeCompany,
    'registrationTypeUser' => l10n.registrationTypeUser,
    'registrationTypeBulkOnboarding' => l10n.registrationTypeBulkOnboarding,
    'registrationSearchHint' => l10n.registrationSearchHint,
    'registrationListEmpty' => l10n.registrationListEmpty,
    'registrationListError' => l10n.registrationListError,
    'registrationDetailError' => l10n.registrationDetailError,
    'registrationMockDataBadge' => l10n.registrationMockDataBadge,
    'registrationSubmittedAt' => l10n.registrationSubmittedAt(params['date'] ?? ''),
    'registrationSectionCompany' => l10n.registrationSectionCompany,
    'registrationSectionContact' => l10n.registrationSectionContact,
    'registrationSectionStatus' => l10n.registrationSectionStatus,
    'registrationSectionAiReview' => l10n.registrationSectionAiReview,
    'registrationSectionDocuments' => l10n.registrationSectionDocuments,
    'registrationFieldCompanyName' => l10n.registrationFieldCompanyName,
    'registrationFieldCountry' => l10n.registrationFieldCountry,
    'registrationFieldVatNumber' => l10n.registrationFieldVatNumber,
    'registrationFieldRegistrationNumber' => l10n.registrationFieldRegistrationNumber,
    'registrationFieldContactName' => l10n.registrationFieldContactName,
    'registrationFieldContactEmail' => l10n.registrationFieldContactEmail,
    'registrationFieldSubmittedAt' => l10n.registrationFieldSubmittedAt,
    'registrationFieldReviewedAt' => l10n.registrationFieldReviewedAt,
    'registrationFieldReviewedBy' => l10n.registrationFieldReviewedBy,
    'registrationFieldAiRecommendation' => l10n.registrationFieldAiRecommendation,
    'registrationFieldAiSummary' => l10n.registrationFieldAiSummary,
    'registrationFieldMissingInformation' => l10n.registrationFieldMissingInformation,
    'registrationFieldDuplicateWarnings' => l10n.registrationFieldDuplicateWarnings,
    'registrationFieldRiskFlags' => l10n.registrationFieldRiskFlags,
    'registrationNoneReported' => l10n.registrationNoneReported,
    'registrationDocumentsMetadataOnly' => l10n.registrationDocumentsMetadataOnly,
    'registrationDocumentsEmpty' => l10n.registrationDocumentsEmpty,
    'registrationActionApprove' => l10n.registrationActionApprove,
    'registrationActionReject' => l10n.registrationActionReject,
    'registrationActionRequestInfo' => l10n.registrationActionRequestInfo,
    'registrationDecisionApproveTitle' => l10n.registrationDecisionApproveTitle,
    'registrationDecisionRejectTitle' => l10n.registrationDecisionRejectTitle,
    'registrationDecisionRequestInfoTitle' => l10n.registrationDecisionRequestInfoTitle,
    'registrationDecisionApproveBody' => l10n.registrationDecisionApproveBody,
    'registrationDecisionAuditNotice' => l10n.registrationDecisionAuditNotice,
    'registrationDecisionNotesLabel' => l10n.registrationDecisionNotesLabel,
    'registrationDecisionNotesRequired' => l10n.registrationDecisionNotesRequired,
    'registrationDecisionCancel' => l10n.registrationDecisionCancel,
    'registrationDecisionApproveConfirm' => l10n.registrationDecisionApproveConfirm,
    'registrationDecisionRejectConfirm' => l10n.registrationDecisionRejectConfirm,
    'registrationDecisionRequestInfoConfirm' =>
      l10n.registrationDecisionRequestInfoConfirm,
    'registrationDecisionSuccess' => l10n.registrationDecisionSuccess,
    'registrationDecisionError' => l10n.registrationDecisionError,
    _ => l10n.errorGenericBody,
  };
}

String roleLabel(BuildContext context, String roleKey) =>
    resolveLocalizationKey(context, roleKey);

String resolveSystemHealthKey(
  BuildContext context,
  String key, {
  Map<String, String> params = const {},
}) {
  final l10n = AppLocalizations.of(context);
  return switch (key) {
    'systemHealthLoadError' => l10n.systemHealthLoadError,
    'systemHealthActionUnavailable' => l10n.systemHealthActionUnavailable,
    'systemHealthMockDataBadge' => l10n.systemHealthMockDataBadge,
    'systemHealthServicesTitle' => l10n.systemHealthServicesTitle,
    'systemHealthEventsTitle' => l10n.systemHealthEventsTitle,
    'systemHealthEventsEmpty' => l10n.systemHealthEventsEmpty,
    'systemHealthEventDetailTitle' => l10n.systemHealthEventDetailTitle,
    'systemHealthEventStartedAt' => l10n.systemHealthEventStartedAt(params['date'] ?? ''),
    'systemHealthOpenModule' => l10n.systemHealthOpenModule,
    'systemHealthOverallStatusLabel' => l10n.systemHealthOverallStatusLabel(params['status'] ?? ''),
    'systemHealthLastUpdated' => l10n.systemHealthLastUpdated(params['date'] ?? ''),
    'systemHealthMetricHealthyServices' => l10n.systemHealthMetricHealthyServices,
    'systemHealthMetricWarningServices' => l10n.systemHealthMetricWarningServices,
    'systemHealthMetricCriticalServices' => l10n.systemHealthMetricCriticalServices,
    'systemHealthMetricCriticalEvents' => l10n.systemHealthMetricCriticalEvents,
    'systemHealthMetricWarningEvents' => l10n.systemHealthMetricWarningEvents,
    'systemHealthMetricFailedJobs' => l10n.systemHealthMetricFailedJobs,
    'systemHealthSeverityInfo' => l10n.systemHealthSeverityInfo,
    'systemHealthSeverityWarning' => l10n.systemHealthSeverityWarning,
    'systemHealthSeverityCritical' => l10n.systemHealthSeverityCritical,
    'systemHealthSeverityUnknown' => l10n.systemHealthSeverityUnknown,
    'systemHealthOverallHealthy' => l10n.systemHealthOverallHealthy,
    'systemHealthOverallDegraded' => l10n.systemHealthOverallDegraded,
    'systemHealthOverallCritical' => l10n.systemHealthOverallCritical,
    'systemHealthOverallUnknown' => l10n.systemHealthOverallUnknown,
    'systemHealthFilterAll' => l10n.systemHealthFilterAll,
    'systemHealthFilterCritical' => l10n.systemHealthFilterCritical,
    'systemHealthFilterWarning' => l10n.systemHealthFilterWarning,
    'systemHealthFilterOpen' => l10n.systemHealthFilterOpen,
    'systemHealthFilterAcknowledged' => l10n.systemHealthFilterAcknowledged,
    'systemHealthFilterResolved' => l10n.systemHealthFilterResolved,
    'systemHealthFilterTenantImpacting' => l10n.systemHealthFilterTenantImpacting,
    'systemHealthEventStatusOpen' => l10n.systemHealthEventStatusOpen,
    'systemHealthEventStatusAcknowledged' => l10n.systemHealthEventStatusAcknowledged,
    'systemHealthEventStatusInvestigating' => l10n.systemHealthEventStatusInvestigating,
    'systemHealthEventStatusResolved' => l10n.systemHealthEventStatusResolved,
    'systemHealthEventStatusUnknown' => l10n.systemHealthEventStatusUnknown,
    'systemHealthImpactNone' => l10n.systemHealthImpactNone,
    'systemHealthImpactSingleTenant' => l10n.systemHealthImpactSingleTenant,
    'systemHealthImpactMultipleTenants' => l10n.systemHealthImpactMultipleTenants,
    'systemHealthImpactPlatformWide' => l10n.systemHealthImpactPlatformWide,
    'systemHealthImpactUnknown' => l10n.systemHealthImpactUnknown,
    'systemHealthServiceBackendApi' => l10n.systemHealthServiceBackendApi,
    'systemHealthServiceDatabase' => l10n.systemHealthServiceDatabase,
    'systemHealthServiceDocumentStorage' => l10n.systemHealthServiceDocumentStorage,
    'systemHealthServiceBackgroundWorkers' => l10n.systemHealthServiceBackgroundWorkers,
    'systemHealthServiceAiOcrWorkers' => l10n.systemHealthServiceAiOcrWorkers,
    'systemHealthServiceTranslationService' => l10n.systemHealthServiceTranslationService,
    'systemHealthServiceEmailService' => l10n.systemHealthServiceEmailService,
    'systemHealthServicePushNotificationService' => l10n.systemHealthServicePushNotificationService,
    'systemHealthServiceQueueSystem' => l10n.systemHealthServiceQueueSystem,
    'systemHealthServiceAuthService' => l10n.systemHealthServiceAuthService,
    'systemHealthAiDiagnosticTitle' => l10n.systemHealthAiDiagnosticTitle,
    'systemHealthAiAdvisoryOnly' => l10n.systemHealthAiAdvisoryOnly,
    'systemHealthRecommendedAction' => l10n.systemHealthRecommendedAction,
    'systemHealthActionAcknowledgeTitle' => l10n.systemHealthActionAcknowledgeTitle,
    'systemHealthActionEscalateTitle' => l10n.systemHealthActionEscalateTitle,
    'systemHealthActionAuditNotice' => l10n.systemHealthActionAuditNotice,
    'systemHealthActionNoAutoRepair' => l10n.systemHealthActionNoAutoRepair,
    'systemHealthActionNoteLabel' => l10n.systemHealthActionNoteLabel,
    'systemHealthActionNoteRequired' => l10n.systemHealthActionNoteRequired,
    'systemHealthActionAcknowledgeBody' => l10n.systemHealthActionAcknowledgeBody,
    'systemHealthActionCancel' => l10n.systemHealthActionCancel,
    'systemHealthActionAcknowledgeConfirm' => l10n.systemHealthActionAcknowledgeConfirm,
    'systemHealthActionEscalateConfirm' => l10n.systemHealthActionEscalateConfirm,
    'systemHealthActionAcknowledge' => l10n.systemHealthActionAcknowledge,
    'systemHealthActionEscalate' => l10n.systemHealthActionEscalate,
    'systemHealthActionSuccess' => l10n.systemHealthActionSuccess,
    'systemHealthActionError' => l10n.systemHealthActionError,
    'systemHealthCreateTicketDisabled' => l10n.systemHealthCreateTicketDisabled,
    'systemHealthCreateTicket' => l10n.systemHealthCreateTicket,
    'systemHealthPrivacyNotice' => l10n.systemHealthPrivacyNotice,
    'systemHealthFieldServiceName' => l10n.systemHealthFieldServiceName,
    'systemHealthFieldTenantImpact' => l10n.systemHealthFieldTenantImpact,
    'systemHealthFieldAffectedCompany' => l10n.systemHealthFieldAffectedCompany,
    'systemHealthFieldStartedAt' => l10n.systemHealthFieldStartedAt,
    'systemHealthFieldLastSeenAt' => l10n.systemHealthFieldLastSeenAt,
    'systemHealthFieldResolvedAt' => l10n.systemHealthFieldResolvedAt,
    'systemHealthFieldFailedJobs' => l10n.systemHealthFieldFailedJobs,
    'systemHealthFieldCorrelationId' => l10n.systemHealthFieldCorrelationId,
    _ => l10n.errorGenericBody,
  };
}

String resolveSupportKey(
  BuildContext context,
  String key, {
  Map<String, String> params = const {},
}) {
  final l10n = AppLocalizations.of(context);
  return switch (key) {
    'supportLoadError' => l10n.supportLoadError,
    'supportActionUnavailable' => l10n.supportActionUnavailable,
    'supportActionError' => l10n.supportActionError,
    'supportActionSuccess' => l10n.supportActionSuccess,
    'supportMockDataBadge' => l10n.supportMockDataBadge,
    'supportOpenModule' => l10n.supportOpenModule,
    'supportPrivacyNotice' => l10n.supportPrivacyNotice,
    'supportActionAuditNotice' => l10n.supportActionAuditNotice,
    'supportActionNoteLabel' => l10n.supportActionNoteLabel,
    'supportActionNoteRequired' => l10n.supportActionNoteRequired,
    'supportActionCancel' => l10n.supportActionCancel,
    'supportTicketSearchHint' => l10n.supportTicketSearchHint,
    'supportTicketListEmpty' => l10n.supportTicketListEmpty,
    'supportTicketLastActivity' => l10n.supportTicketLastActivity(params['date'] ?? ''),
    'supportTicketDetailTitle' => l10n.supportTicketDetailTitle,
    'supportGrantDetailTitle' => l10n.supportGrantDetailTitle,
    'supportGrantSearchHint' => l10n.supportGrantSearchHint,
    'supportGrantListEmpty' => l10n.supportGrantListEmpty,
    'supportGrantScopeIdLabel' => l10n.supportGrantScopeIdLabel(params['id'] ?? ''),
    'supportGrantExpiresAt' => l10n.supportGrantExpiresAt(params['date'] ?? ''),
    'supportSummaryTitle' => l10n.supportSummaryTitle,
    'supportSummaryOpenTickets' => l10n.supportSummaryOpenTickets,
    'supportSummaryUrgentCritical' => l10n.supportSummaryUrgentCritical,
    'supportSummaryActiveGrants' => l10n.supportSummaryActiveGrants,
    'supportSummaryLastUpdated' => l10n.supportSummaryLastUpdated(params['date'] ?? ''),
    'supportTicketCreateSuccess' => l10n.supportTicketCreateSuccess,
    'supportTicketFilterAll' => l10n.supportTicketFilterAll,
    'supportTicketFilterOpen' => l10n.supportTicketFilterOpen,
    'supportTicketFilterUrgent' => l10n.supportTicketFilterUrgent,
    'supportTicketFilterCritical' => l10n.supportTicketFilterCritical,
    'supportTicketFilterSystemHealth' => l10n.supportTicketFilterSystemHealth,
    'supportTicketFilterWaitingForCustomer' => l10n.supportTicketFilterWaitingForCustomer,
    'supportTicketFilterResolved' => l10n.supportTicketFilterResolved,
    'supportGrantFilterAll' => l10n.supportGrantFilterAll,
    'supportGrantFilterPending' => l10n.supportGrantFilterPending,
    'supportGrantFilterActive' => l10n.supportGrantFilterActive,
    'supportGrantFilterExpired' => l10n.supportGrantFilterExpired,
    'supportGrantFilterRevoked' => l10n.supportGrantFilterRevoked,
    'supportTicketStatusOpen' => l10n.supportTicketStatusOpen,
    'supportTicketStatusAcknowledged' => l10n.supportTicketStatusAcknowledged,
    'supportTicketStatusInvestigating' => l10n.supportTicketStatusInvestigating,
    'supportTicketStatusWaitingForCustomer' => l10n.supportTicketStatusWaitingForCustomer,
    'supportTicketStatusResolved' => l10n.supportTicketStatusResolved,
    'supportTicketStatusClosed' => l10n.supportTicketStatusClosed,
    'supportTicketStatusUnknown' => l10n.supportTicketStatusUnknown,
    'supportTicketPriorityLow' => l10n.supportTicketPriorityLow,
    'supportTicketPriorityNormal' => l10n.supportTicketPriorityNormal,
    'supportTicketPriorityHigh' => l10n.supportTicketPriorityHigh,
    'supportTicketPriorityUrgent' => l10n.supportTicketPriorityUrgent,
    'supportTicketPriorityCritical' => l10n.supportTicketPriorityCritical,
    'supportTicketPriorityUnknown' => l10n.supportTicketPriorityUnknown,
    'supportTicketCategoryRegistration' => l10n.supportTicketCategoryRegistration,
    'supportTicketCategorySystemHealth' => l10n.supportTicketCategorySystemHealth,
    'supportTicketCategoryUploadIssue' => l10n.supportTicketCategoryUploadIssue,
    'supportTicketCategoryBilling' => l10n.supportTicketCategoryBilling,
    'supportTicketCategoryAccess' => l10n.supportTicketCategoryAccess,
    'supportTicketCategoryIntegration' => l10n.supportTicketCategoryIntegration,
    'supportTicketCategoryOther' => l10n.supportTicketCategoryOther,
    'supportTicketCategoryUnknown' => l10n.supportTicketCategoryUnknown,
    'supportGrantStatusPending' => l10n.supportGrantStatusPending,
    'supportGrantStatusActive' => l10n.supportGrantStatusActive,
    'supportGrantStatusExpired' => l10n.supportGrantStatusExpired,
    'supportGrantStatusRevoked' => l10n.supportGrantStatusRevoked,
    'supportGrantStatusDenied' => l10n.supportGrantStatusDenied,
    'supportGrantStatusUnknown' => l10n.supportGrantStatusUnknown,
    'supportScopeCompanyMetadata' => l10n.supportScopeCompanyMetadata,
    'supportScopeSpecificTrip' => l10n.supportScopeSpecificTrip,
    'supportScopeSpecificDocumentIssue' => l10n.supportScopeSpecificDocumentIssue,
    'supportScopeUploadQueueIssue' => l10n.supportScopeUploadQueueIssue,
    'supportScopeSystemHealthIssue' => l10n.supportScopeSystemHealthIssue,
    'supportScopeIntegrationIssue' => l10n.supportScopeIntegrationIssue,
    'supportScopeBillingIssue' => l10n.supportScopeBillingIssue,
    'supportScopeUnknown' => l10n.supportScopeUnknown,
    'supportGrantWarningTitle' => l10n.supportGrantWarningTitle,
    'supportGrantWarningBody' => l10n.supportGrantWarningBody,
    'supportGrantAuditNotice' => l10n.supportGrantAuditNotice,
    'supportGrantCreateTitle' => l10n.supportGrantCreateTitle,
    'supportGrantCreateWarning' => l10n.supportGrantCreateWarning,
    'supportGrantCreateConfirm' => l10n.supportGrantCreateConfirm,
    'supportGrantCreateSuccess' => l10n.supportGrantCreateSuccess,
    'supportGrantCompanyLabel' => l10n.supportGrantCompanyLabel(params['name'] ?? ''),
    'supportGrantScopeTypeLabel' => l10n.supportGrantScopeTypeLabel,
    'supportGrantScopeIdFieldLabel' => l10n.supportGrantScopeIdFieldLabel,
    'supportGrantScopeIdRequired' => l10n.supportGrantScopeIdRequired,
    'supportGrantReasonLabel' => l10n.supportGrantReasonLabel,
    'supportGrantReasonRequired' => l10n.supportGrantReasonRequired,
    'supportGrantExpiryRequired' => l10n.supportGrantExpiryRequired,
    'supportGrantBroadAccessRejected' => l10n.supportGrantBroadAccessRejected,
    'supportGrantExpiryLabel' => l10n.supportGrantExpiryLabel,
    'supportGrantExpiryTwoHours' => l10n.supportGrantExpiryTwoHours,
    'supportGrantExpiryTwentyFourHours' => l10n.supportGrantExpiryTwentyFourHours,
    'supportGrantRevokeTitle' => l10n.supportGrantRevokeTitle,
    'supportGrantRevokeNoteLabel' => l10n.supportGrantRevokeNoteLabel,
    'supportGrantRevokeConfirm' => l10n.supportGrantRevokeConfirm,
    'supportGrantRevokeSuccess' => l10n.supportGrantRevokeSuccess,
    'supportGrantActionRevoke' => l10n.supportGrantActionRevoke,
    'supportGrantFieldCompany' => l10n.supportGrantFieldCompany,
    'supportGrantFieldScopeId' => l10n.supportGrantFieldScopeId,
    'supportGrantFieldReason' => l10n.supportGrantFieldReason,
    'supportGrantFieldAllowedCategories' => l10n.supportGrantFieldAllowedCategories,
    'supportGrantFieldExcludesDocuments' => l10n.supportGrantFieldExcludesDocuments,
    'supportGrantFieldCreatedAt' => l10n.supportGrantFieldCreatedAt,
    'supportGrantFieldExpiresAt' => l10n.supportGrantFieldExpiresAt,
    'supportGrantFieldRevokedAt' => l10n.supportGrantFieldRevokedAt,
    'supportGrantFieldApprovedBy' => l10n.supportGrantFieldApprovedBy,
    'supportGrantFieldAuditLogId' => l10n.supportGrantFieldAuditLogId,
    'supportGrantYes' => l10n.supportGrantYes,
    'supportGrantNo' => l10n.supportGrantNo,
    'supportTicketFieldCompany' => l10n.supportTicketFieldCompany,
    'supportTicketFieldRequester' => l10n.supportTicketFieldRequester,
    'supportTicketFieldCategory' => l10n.supportTicketFieldCategory,
    'supportTicketFieldSummary' => l10n.supportTicketFieldSummary,
    'supportTicketFieldCreatedAt' => l10n.supportTicketFieldCreatedAt,
    'supportTicketFieldUpdatedAt' => l10n.supportTicketFieldUpdatedAt,
    'supportTicketFieldLastActivity' => l10n.supportTicketFieldLastActivity,
    'supportTicketFieldLinkedHealthEvent' => l10n.supportTicketFieldLinkedHealthEvent,
    'supportTicketFieldSupportGrant' => l10n.supportTicketFieldSupportGrant,
    'supportTicketActionAcknowledge' => l10n.supportTicketActionAcknowledge,
    'supportTicketActionClose' => l10n.supportTicketActionClose,
    'supportTicketActionCreateGrant' => l10n.supportTicketActionCreateGrant,
    'supportTicketActionAcknowledgeTitle' => l10n.supportTicketActionAcknowledgeTitle,
    'supportTicketActionCloseTitle' => l10n.supportTicketActionCloseTitle,
    'supportTicketActionAcknowledgeBody' => l10n.supportTicketActionAcknowledgeBody,
    'supportTicketActionAcknowledgeConfirm' => l10n.supportTicketActionAcknowledgeConfirm,
    'supportTicketActionCloseConfirm' => l10n.supportTicketActionCloseConfirm,
    _ => l10n.errorGenericBody,
  };
}
