import 'package:flutter/material.dart';

import '../../l10n/app_localizations.dart';
import '../localization/localization_keys.dart';

String resolveLocalizationKey(BuildContext context, String key) {
  final l10n = AppLocalizations.of(context);
  return switch (key) {
    LocalizationKeys.authEmail => l10n.authEmail,
    LocalizationKeys.authPassword => l10n.authPassword,
    LocalizationKeys.authSignIn => l10n.authSignIn,
    LocalizationKeys.authSigningIn => l10n.authSigningIn,
    LocalizationKeys.authLogout => l10n.authLogout,
    LocalizationKeys.authInvalidCredentials => l10n.authInvalidCredentials,
    LocalizationKeys.authNetworkError => l10n.authNetworkError,
    LocalizationKeys.authServerError => l10n.authServerError,
    LocalizationKeys.authForbiddenRole => l10n.authForbiddenRole,
    LocalizationKeys.authBackendNotConfigured => l10n.authBackendNotConfigured,
    LocalizationKeys.authRequiredField => l10n.authRequiredField,
    LocalizationKeys.authShowPassword => l10n.authShowPassword,
    LocalizationKeys.authHidePassword => l10n.authHidePassword,
    LocalizationKeys.errorGenericBody => l10n.errorGenericBody,
    LocalizationKeys.roleSuperAdmin => l10n.roleSuperAdmin,
    LocalizationKeys.roleSupportAdmin => l10n.roleSupportAdmin,
    LocalizationKeys.roleOnboardingReviewer => l10n.roleOnboardingReviewer,
    LocalizationKeys.roleBillingAdmin => l10n.roleBillingAdmin,
    LocalizationKeys.systemHealthLoadError => l10n.systemHealthLoadError,
    LocalizationKeys.systemHealthActionUnavailable => l10n.systemHealthActionUnavailable,
    _ => l10n.errorGenericBody,
  };
}

String resolveRegistrationKey(
  BuildContext context,
  String key, {
  Map<String, String> params = const {},
}) {
  final l10n = AppLocalizations.of(context);
  return switch (key) {
    'registrationFilterAll' => l10n.registrationFilterAll,
    'registrationFilterPending' => l10n.registrationFilterPending,
    'registrationFilterNeedsInfo' => l10n.registrationFilterNeedsInfo,
    'registrationFilterAiReviewed' => l10n.registrationFilterAiReviewed,
    'registrationFilterApproved' => l10n.registrationFilterApproved,
    'registrationFilterRejected' => l10n.registrationFilterRejected,
    'registrationFilterHighRisk' => l10n.registrationFilterHighRisk,
    'registrationStatusPending' => l10n.registrationStatusPending,
    'registrationStatusNeedsInfo' => l10n.registrationStatusNeedsInfo,
    'registrationStatusApproved' => l10n.registrationStatusApproved,
    'registrationStatusRejected' => l10n.registrationStatusRejected,
    'registrationStatusCancelled' => l10n.registrationStatusCancelled,
    'registrationStatusUnknown' => l10n.registrationStatusUnknown,
    'registrationRiskLow' => l10n.registrationRiskLow,
    'registrationRiskMedium' => l10n.registrationRiskMedium,
    'registrationRiskHigh' => l10n.registrationRiskHigh,
    'registrationRiskUnknown' => l10n.registrationRiskUnknown,
    'registrationTypeCompany' => l10n.registrationTypeCompany,
    'registrationTypeUser' => l10n.registrationTypeUser,
    'registrationTypeBulkOnboarding' => l10n.registrationTypeBulkOnboarding,
    'registrationSearchHint' => l10n.registrationSearchHint,
    'registrationListEmpty' => l10n.registrationListEmpty,
    'registrationListError' => l10n.registrationListError,
    'registrationDetailError' => l10n.registrationDetailError,
    'registrationMockDataBadge' => l10n.registrationMockDataBadge,
    'registrationSubmittedAt' => l10n.registrationSubmittedAt(params['date'] ?? ''),
    'registrationSectionCompany' => l10n.registrationSectionCompany,
    'registrationSectionContact' => l10n.registrationSectionContact,
    'registrationSectionStatus' => l10n.registrationSectionStatus,
    'registrationSectionAiReview' => l10n.registrationSectionAiReview,
    'registrationSectionDocuments' => l10n.registrationSectionDocuments,
    'registrationFieldCompanyName' => l10n.registrationFieldCompanyName,
    'registrationFieldCountry' => l10n.registrationFieldCountry,
    'registrationFieldVatNumber' => l10n.registrationFieldVatNumber,
    'registrationFieldRegistrationNumber' => l10n.registrationFieldRegistrationNumber,
    'registrationFieldContactName' => l10n.registrationFieldContactName,
    'registrationFieldContactEmail' => l10n.registrationFieldContactEmail,
    'registrationFieldSubmittedAt' => l10n.registrationFieldSubmittedAt,
    'registrationFieldReviewedAt' => l10n.registrationFieldReviewedAt,
    'registrationFieldReviewedBy' => l10n.registrationFieldReviewedBy,
    'registrationFieldAiRecommendation' => l10n.registrationFieldAiRecommendation,
    'registrationFieldAiSummary' => l10n.registrationFieldAiSummary,
    'registrationFieldMissingInformation' => l10n.registrationFieldMissingInformation,
    'registrationFieldDuplicateWarnings' => l10n.registrationFieldDuplicateWarnings,
    'registrationFieldRiskFlags' => l10n.registrationFieldRiskFlags,
    'registrationNoneReported' => l10n.registrationNoneReported,
    'registrationDocumentsMetadataOnly' => l10n.registrationDocumentsMetadataOnly,
    'registrationDocumentsEmpty' => l10n.registrationDocumentsEmpty,
    'registrationActionApprove' => l10n.registrationActionApprove,
    'registrationActionReject' => l10n.registrationActionReject,
    'registrationActionRequestInfo' => l10n.registrationActionRequestInfo,
    'registrationDecisionApproveTitle' => l10n.registrationDecisionApproveTitle,
    'registrationDecisionRejectTitle' => l10n.registrationDecisionRejectTitle,
    'registrationDecisionRequestInfoTitle' => l10n.registrationDecisionRequestInfoTitle,
    'registrationDecisionApproveBody' => l10n.registrationDecisionApproveBody,
    'registrationDecisionAuditNotice' => l10n.registrationDecisionAuditNotice,
    'registrationDecisionNotesLabel' => l10n.registrationDecisionNotesLabel,
    'registrationDecisionNotesRequired' => l10n.registrationDecisionNotesRequired,
    'registrationDecisionCancel' => l10n.registrationDecisionCancel,
    'registrationDecisionApproveConfirm' => l10n.registrationDecisionApproveConfirm,
    'registrationDecisionRejectConfirm' => l10n.registrationDecisionRejectConfirm,
    'registrationDecisionRequestInfoConfirm' =>
      l10n.registrationDecisionRequestInfoConfirm,
    'registrationDecisionSuccess' => l10n.registrationDecisionSuccess,
    'registrationDecisionError' => l10n.registrationDecisionError,
    _ => l10n.errorGenericBody,
  };
}

String roleLabel(BuildContext context, String roleKey) =>
    resolveLocalizationKey(context, roleKey);

String resolveSystemHealthKey(
  BuildContext context,
  String key, {
  Map<String, String> params = const {},
}) {
  final l10n = AppLocalizations.of(context);
  return switch (key) {
    'systemHealthLoadError' => l10n.systemHealthLoadError,
    'systemHealthActionUnavailable' => l10n.systemHealthActionUnavailable,
    'systemHealthMockDataBadge' => l10n.systemHealthMockDataBadge,
    'systemHealthServicesTitle' => l10n.systemHealthServicesTitle,
    'systemHealthEventsTitle' => l10n.systemHealthEventsTitle,
    'systemHealthEventsEmpty' => l10n.systemHealthEventsEmpty,
    'systemHealthEventDetailTitle' => l10n.systemHealthEventDetailTitle,
    'systemHealthEventStartedAt' => l10n.systemHealthEventStartedAt(params['date'] ?? ''),
    'systemHealthOpenModule' => l10n.systemHealthOpenModule,
    'systemHealthOverallStatusLabel' => l10n.systemHealthOverallStatusLabel(params['status'] ?? ''),
    'systemHealthLastUpdated' => l10n.systemHealthLastUpdated(params['date'] ?? ''),
    'systemHealthMetricHealthyServices' => l10n.systemHealthMetricHealthyServices,
    'systemHealthMetricWarningServices' => l10n.systemHealthMetricWarningServices,
    'systemHealthMetricCriticalServices' => l10n.systemHealthMetricCriticalServices,
    'systemHealthMetricCriticalEvents' => l10n.systemHealthMetricCriticalEvents,
    'systemHealthMetricWarningEvents' => l10n.systemHealthMetricWarningEvents,
    'systemHealthMetricFailedJobs' => l10n.systemHealthMetricFailedJobs,
    'systemHealthSeverityInfo' => l10n.systemHealthSeverityInfo,
    'systemHealthSeverityWarning' => l10n.systemHealthSeverityWarning,
    'systemHealthSeverityCritical' => l10n.systemHealthSeverityCritical,
    'systemHealthSeverityUnknown' => l10n.systemHealthSeverityUnknown,
    'systemHealthOverallHealthy' => l10n.systemHealthOverallHealthy,
    'systemHealthOverallDegraded' => l10n.systemHealthOverallDegraded,
    'systemHealthOverallCritical' => l10n.systemHealthOverallCritical,
    'systemHealthOverallUnknown' => l10n.systemHealthOverallUnknown,
    'systemHealthFilterAll' => l10n.systemHealthFilterAll,
    'systemHealthFilterCritical' => l10n.systemHealthFilterCritical,
    'systemHealthFilterWarning' => l10n.systemHealthFilterWarning,
    'systemHealthFilterOpen' => l10n.systemHealthFilterOpen,
    'systemHealthFilterAcknowledged' => l10n.systemHealthFilterAcknowledged,
    'systemHealthFilterResolved' => l10n.systemHealthFilterResolved,
    'systemHealthFilterTenantImpacting' => l10n.systemHealthFilterTenantImpacting,
    'systemHealthEventStatusOpen' => l10n.systemHealthEventStatusOpen,
    'systemHealthEventStatusAcknowledged' => l10n.systemHealthEventStatusAcknowledged,
    'systemHealthEventStatusInvestigating' => l10n.systemHealthEventStatusInvestigating,
    'systemHealthEventStatusResolved' => l10n.systemHealthEventStatusResolved,
    'systemHealthEventStatusUnknown' => l10n.systemHealthEventStatusUnknown,
    'systemHealthImpactNone' => l10n.systemHealthImpactNone,
    'systemHealthImpactSingleTenant' => l10n.systemHealthImpactSingleTenant,
    'systemHealthImpactMultipleTenants' => l10n.systemHealthImpactMultipleTenants,
    'systemHealthImpactPlatformWide' => l10n.systemHealthImpactPlatformWide,
    'systemHealthImpactUnknown' => l10n.systemHealthImpactUnknown,
    'systemHealthServiceBackendApi' => l10n.systemHealthServiceBackendApi,
    'systemHealthServiceDatabase' => l10n.systemHealthServiceDatabase,
    'systemHealthServiceDocumentStorage' => l10n.systemHealthServiceDocumentStorage,
    'systemHealthServiceBackgroundWorkers' => l10n.systemHealthServiceBackgroundWorkers,
    'systemHealthServiceAiOcrWorkers' => l10n.systemHealthServiceAiOcrWorkers,
    'systemHealthServiceTranslationService' => l10n.systemHealthServiceTranslationService,
    'systemHealthServiceEmailService' => l10n.systemHealthServiceEmailService,
    'systemHealthServicePushNotificationService' => l10n.systemHealthServicePushNotificationService,
    'systemHealthServiceQueueSystem' => l10n.systemHealthServiceQueueSystem,
    'systemHealthServiceAuthService' => l10n.systemHealthServiceAuthService,
    'systemHealthAiDiagnosticTitle' => l10n.systemHealthAiDiagnosticTitle,
    'systemHealthAiAdvisoryOnly' => l10n.systemHealthAiAdvisoryOnly,
    'systemHealthRecommendedAction' => l10n.systemHealthRecommendedAction,
    'systemHealthActionAcknowledgeTitle' => l10n.systemHealthActionAcknowledgeTitle,
    'systemHealthActionEscalateTitle' => l10n.systemHealthActionEscalateTitle,
    'systemHealthActionAuditNotice' => l10n.systemHealthActionAuditNotice,
    'systemHealthActionNoAutoRepair' => l10n.systemHealthActionNoAutoRepair,
    'systemHealthActionNoteLabel' => l10n.systemHealthActionNoteLabel,
    'systemHealthActionNoteRequired' => l10n.systemHealthActionNoteRequired,
    'systemHealthActionAcknowledgeBody' => l10n.systemHealthActionAcknowledgeBody,
    'systemHealthActionCancel' => l10n.systemHealthActionCancel,
    'systemHealthActionAcknowledgeConfirm' => l10n.systemHealthActionAcknowledgeConfirm,
    'systemHealthActionEscalateConfirm' => l10n.systemHealthActionEscalateConfirm,
    'systemHealthActionAcknowledge' => l10n.systemHealthActionAcknowledge,
    'systemHealthActionEscalate' => l10n.systemHealthActionEscalate,
    'systemHealthActionSuccess' => l10n.systemHealthActionSuccess,
    'systemHealthActionError' => l10n.systemHealthActionError,
    'systemHealthCreateTicketDisabled' => l10n.systemHealthCreateTicketDisabled,
    'systemHealthPrivacyNotice' => l10n.systemHealthPrivacyNotice,
    'systemHealthFieldServiceName' => l10n.systemHealthFieldServiceName,
    'systemHealthFieldTenantImpact' => l10n.systemHealthFieldTenantImpact,
    'systemHealthFieldAffectedCompany' => l10n.systemHealthFieldAffectedCompany,
    'systemHealthFieldStartedAt' => l10n.systemHealthFieldStartedAt,
    'systemHealthFieldLastSeenAt' => l10n.systemHealthFieldLastSeenAt,
    'systemHealthFieldResolvedAt' => l10n.systemHealthFieldResolvedAt,
    'systemHealthFieldFailedJobs' => l10n.systemHealthFieldFailedJobs,
    'systemHealthFieldCorrelationId' => l10n.systemHealthFieldCorrelationId,
    _ => l10n.errorGenericBody,
  };
}
